---

- name: Exit if map_token is not defined
  fail:
    msg: Need to specify a value for map_token variable
  when: >
    map_token is not defined or
    map_token is none or
    map_token|trim() == ""

- name: "Refresh {{ install_dir }}"
  file:
    path: "{{ install_dir }}"
    state: absent
    mode: '0755'
- file:
    path: "{{ install_dir }}"
    state: directory
    mode: '0755'

- name: "Clone {{ release_tag }} of er-demo installer from {{ er_demo_ansible_playbook_url }} to {{ install_dir }}"
  shell: |
    git clone --depth 1 --branch {{ release_tag }} {{ er_demo_ansible_playbook_url }} {{ install_dir }}

- name: pre_workload tasks complete
  debug:
    msg: "Pre-Workload tasks completed successfully."
  when: not silent|bool
